#!/usr/bin/env zsh
#
# Finalize vim configuration
#

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

# Install/update plugins
vim +PluginInstall\! +qall
vim +PluginClean\! +qall

# Re-compile YouCompleteMe
YCMDir="${moduledir}/dotfiles/vim/bundle/YouCompleteMe"
if [ -d "$YCMDir" ]; then
    (
        if [ ! -f "${YCMDir}/third_party/ycmd/ycm_core.so" -o "${YCMDir}/third_party" -nt "${YCMDir}/third_party/ycmd/ycm_core.so" ]; then
            carapace-message "yellow" "(Re-)compiling YouCompleteMe plugin."
            cd "$YCMDir"
            python3 install.py --all 1> /dev/null 2> /dev/null || :  # We don't care about failing on this failure
        fi
    )
fi

# Install vim-go binaries
goenv_cache="${HOME}/bin/carapace/goenv-cache"

if [ -r "${goenv_cache}" ]; then
    source "${goenv_cache}"

    if [ -d "${GOROOT}" ]; then
        carapace-message "yellow" "(Re-)installing vim-go binaries."
        vim +GoInstallBinaries\! +qall
    fi
fi

# Update helps
vim +helptags ALL\! +qall

