#!/usr/bin/env zsh
#
# Grab/update the vundle repo
#

repodir="dotfiles/vim/bundle/Vundle.vim"
repo="https://github.com/VundleVim/Vundle.vim.git"

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

mkdir -p ${moduledir}/dotfiles/vim/bundle 2> /dev/null || :

# See if we're already installed
if [ -d "${moduledir}/${repodir}" ]; then
    # Assume the repo exists, update it
    ( cd "${moduledir}/${repodir}" && git pull -q --recurse-submodules )
else
    # Assume the repo does not exist.
    # Shallow: we never need Vundle's history, and this module is already the
    # heaviest in the bundle.
    ( cd "${moduledir}" && git clone --depth 1 --recurse-submodules --shallow-submodules "${repo}" ./${repodir} )
fi

# NOTE: the plugins themselves are cloned by Vundle (from post-install), which
# has no shallow-clone option.  ale alone carries ~20MB of test fixtures for
# languages we don't use.  Switching plugin managers would fix that; see
# docs/TODO.md.


