#!zsh
#
# Use carapaceprompt if installed, default to something terrible otherwise
#

if [ -x "$(which carapaceprompt 2> /dev/null)" ]; then
    export PS1='%{$(carapaceprompt --color --exitcode $?)%}
${Green}--${BCyan}%#${NC} '

else
    export PS1='${Green}--${BCyan}%#${NC} '
fi

