#!zsh
#
# Aliases for toybox commands that don't exist on the system
#

# Load the aliases
if [ -r "${CARAPACE_CURRENT_MODULE_PATH}/tbaliases" ]; then
  source "${CARAPACE_CURRENT_MODULE_PATH}/tbaliases"
fi

# What commands did we set up aliases for?
alias check-toybox-aliases='alias | grep toybox'

