#!zsh

#
# Build a list of git repository start points.  path1:depth,path2:depth,path3:depth
#

export GIT_REPO_SEARCH_PATH=""

add_git_repo_search_path() {
    local repoPath="$1"
    local searchDepth=$2

    if [ -d "$repoPath" -a $searchDepth -gt 0 ]; then
      case "$repoPath" in
        (*"$GIT_REPO_SEARCH_PATH"*)
          # Already in there, skip adding
          ;;
        (*)
          # Add it
          export GIT_REPO_SEARCH_PATH="${GIT_REPO_SEARCH_PATH},${repoPath}:${searchDepth}"
          ;;
      esac
    fi
}

#
# Decent presets?
#

add_git_repo_search_path "$HOME/.carapace" 3
add_git_repo_search_path "$HOME/prj" 3
add_git_repo_search_path "$HOME/go/src/github.com/cheilman" 3
add_git_repo_search_path "$HOME/go/src/bitbucket.org/cheilman" 3

#
# Load repos from host config (if they exist)
#

if [ -f $HOME/.host/config/gitrepos ]; then
    # TODO: Make this smarter, not just executing blindly.  Maybe just pipe each line to add_git_repo_search_path or something.
    . $HOME/.host/config/gitrepos
fi


#
# Use Git's colored diff even for non-git stuff
# From: https://github.com/mathiasbynens/dotfiles/blob/master/.functions
#
hash git &>/dev/null;
if [ $? -eq 0 ]; then
  function diff() {
    git diff --no-index --color-words "$@";
  }
fi;

