#!zsh
#
# Load fzf
#

export FZF_DEFAULT_OPTS='--no-mouse --height=50% --border --ansi --color=16 --black'
export FZF_DEFAULT_COMMAND='ag -al'
export FZF_DEFAULT_WIDGET_HEIGHT='20%'

alias fzfzf='fzf --preview '"'"'[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (highlight -O ansi -l {} || coderay {} || rougify {} || cat {}) 2> /dev/null | head -500'"'"

add_path_back "${CARAPACE_CURRENT_MODULE_PATH}/fzf/bin"

# Setup fzf
# ---------
# Cache the shell integration rather than forking fzf on every startup.
if (( $+commands[fzf] )); then
  _fzf_init_cache="${HOME}/.cache/carapace/fzf-init.zsh"
  if [[ ! -r $_fzf_init_cache || ${commands[fzf]} -nt $_fzf_init_cache ]]; then
    mkdir -p "${_fzf_init_cache:h}" 2>/dev/null || :
    fzf --zsh > "$_fzf_init_cache" 2>/dev/null || :
  fi
  [[ -s $_fzf_init_cache ]] && source "$_fzf_init_cache"
  unset _fzf_init_cache
fi

