#!zsh
#
# Load fzf
#

export FZF_DEFAULT_OPTS='--no-mouse --height=50% --border --ansi --color=16 --black'
export FZF_DEFAULT_COMMAND='ag -al'
export FZF_DEFAULT_WIDGET_HEIGHT='20%'

alias fzfzf='fzf --preview '"'"'[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (highlight -O ansi -l {} || coderay {} || rougify {} || cat {}) 2> /dev/null | head -500'"'"

add_path_back "${CARAPACE_CURRENT_MODULE_PATH}/fzf/bin"

# Setup fzf
# ---------
source <(fzf --zsh)

