#!/usr/bin/env zsh
#
# Prepare to execute the Carapace generated zshrc script
#

# Profiling support
if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

findCarapace() {
    local zshrc="$HOME/.zshrc"
    local carapace="${zshrc:A:h}"

    if [ ! -d "$carapace" ]; then
        carapace="$HOME/.carapace"
    fi

    echo $carapace
}

export CARAPACE="$(findCarapace)"

#
# We'll want to see if we need to switch zsh executables
# ... or not.  Let's just compile/install the right zsh ...
#

#
# Check for new updates
#
which gtouch &>/dev/null
if [ $? -eq 0 ]; then
  alias touch=gtouch
fi

update_freq="9 days"
update_timestamp="$CARAPACE/generated/carapace-update-timestamp"
update_timestamp_now="${update_timestamp}_now"

# Make sure file exists
if [ ! -e "$update_timestamp" ]; then
    touch -d "-$update_freq" "$update_timestamp"
fi

# Check to see if we need to update
touch "$update_timestamp_now"
if [ "$update_timestamp_now" -nt "$update_timestamp" ]; then
    # Need to update
    touch -d "+$update_freq" "$update_timestamp"
    $CARAPACE/install/carapace-update
fi

#
# Execute
#

. $CARAPACE/generated/generated-zshrc

# Profiling support
if [[ "$ZPROF" = true ]]; then
  zprof
fi

