#!/usr/bin/env zsh
#
# Prepare to execute the Carapace generated zshrc script
#

# Profiling support
if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

if which findCarapace &>/dev/null; then
  export CARAPACE="$(findCarapace)"
elif [ -x "${HOME}/bin/carapace/findCarapace" ]; then
  export CARAPACE="$(${HOME}/bin/carapace/findCarapace)"
elif [ -f "${HOME}/.carapace/CARAPACE" ]; then
  export CARAPACE="${HOME}/.carapace"
else
  echo "--!! FAILED TO FIND CARAPACE !!--"
fi

#
# Execute
#

. $CARAPACE/generated/generated-zshrc

# Profiling support
if [[ "$ZPROF" = true ]]; then
  zprof
fi

