#!zsh

#
# Disable ctrl-s flow control
#

[[ $- == *i* ]] && stty -ixon

#
# Force my bin folders to be first
#

add_path_front "$HOME/bin/carapace"
add_path_front "$HOME/bin"
add_path_front "$HOME/.host/bin"

#
# Finalize the path cache file
#

mv -f "$pathCache" "$HOME/.path-carapace"

#
# Re-call zsh highlighting
#
source ${ZGEN_DIR}/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.zsh

#
# oh-my-zsh messes up my 'la' alias
#
alias la='ls -Fa'

#
# on-my-zsh also messes with zsh history
#
HISTSIZE=16000
SAVEHIST=$HISTSIZE
HISTFILE=~/.zshhistory

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_FUNCTIONS
setopt HIST_NO_STORE
setopt HIST_VERIFY
setopt HIST_REDUCE_BLANKS

setopt INC_APPEND_HISTORY_TIME
setopt NO_INC_APPEND_HISTORY
setopt NO_SHARE_HISTORY

