#!zsh

#
# Disable ctrl-s flow control
#

[[ $- == *i* ]] && stty -ixon

#
# Force my bin folders to be first
#

add_path_front "$HOME/bin/carapace"
add_path_front "$HOME/bin"
add_path_front "$HOME/.host/bin"

#
# Finalize the path cache file
#

mv -f "$pathCache" "$HOME/.path-carapace"

