#!zsh

#
# Disable ctrl-s flow control
#

[[ $- == *i* ]] && stty -ixon

#
# Force my bin folders to be first
#

add_path_front "$HOME/bin/carapace"
add_path_front "$HOME/bin"
add_path_front "$HOME/.host/bin"

#
# Re-call zsh highlighting
#
#source ${ZGEN_DIR}/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.zsh

#
# zgen/oh-my-zsh might mess up my ls aliases, so I moved them to post-process
#
# Fancy listing
if which eza &> /dev/null; then
  # Prefer eza
  alias ls='eza'
  alias lf='eza -F --icons --color=auto'
  alias la='eza -F --icons --color=auto --all'
  alias ll='eza -F --icons --color=auto --git --long --group'
  alias lla='eza -F --icons --color=auto --git --long --group --all'
  alias lll='eza -F --icons --color=auto --git --long --group --sort=newest'
else
  # Use something ls-based
  if which gls &> /dev/null; then
    # Try gnu ls
    alias ls='gls --color=auto --dereference-command-line-symlink-to-dir'
  elif ls --dereference-command-line-symlink-to-dir / &> /dev/null; then
    # Ls supports the symlink dereference param
    alias ls='ls --color=auto --dereference-command-line-symlink-to-dir'
  else
    # Plain-ish ls I guess
    alias ls='ls --color=auto'
  fi

  alias lf='ls -F'
  alias la='ls -Fa'
  alias ll='ls -Flh'
  alias lla='ls -Flha'
  alias lll='ls -ltrh'
fi

#
# on-my-zsh also messes with zsh history
#
HISTSIZE=16000
SAVEHIST=$HISTSIZE
HISTFILE=~/.zshhistory

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_FUNCTIONS
setopt HIST_NO_STORE
setopt HIST_VERIFY
setopt HIST_REDUCE_BLANKS

setopt INC_APPEND_HISTORY_TIME
setopt NO_INC_APPEND_HISTORY
setopt NO_SHARE_HISTORY

#
# Save the final path to the cache file and finalize
#
save_path_to_cache
cp -f "$pathCache" "$HOME/.path-carapace"

