#!zsh

#
# Set timezone
#

export TZ='America/New_York'

#
# Editor/Pager
#

export EDITOR=vim
export VISUAL=vim
export PAGER=less

#
# Path
#

if [ -z "$HOME" ]; then
    # From https://stackoverflow.com/a/630645o
    prg=$0
    if [ ! -e "$prg" ]; then
        prg=$(command -v -- "$prg")
    fi
    dir=$(
      cd -P -- "$(dirname -- "$prg")" && pwd -P
    )
    prg=$dir/$(basename -- "$prg")

    if [ -d "$prg" ]; then
        export HOME="$prg"
    fi
fi

if [ -n "$HOME" ]; then
    export PATH=$HOME/bin:$HOME/bin/carapace:$PATH:/usr/bin
fi

#
# TTY settings
#

# Disable ^S/^Q flow control
[[ $- == *i* ]] && stty -ixon

#
# Keyboard settings
#

# Disable caps lock key
[ -x "`which setxkbmap 2>/dev/null`" ] && setxkbmap -option caps:none

#
# Other scripts to run for /bin/sh initialization (specifically for dash)
#
export ENV="$HOME/.shinit"

