#!zsh

#
# We build the path over the course of startup and write it to a well-known
# location at the end (99post), so non-shell things can source a valid PATH.
#
# NOTE: this used to mktemp at the top of every shell and cat into it.  Both
# were forks on the critical path; zsh can do all of it in-process.
#

zmodload -F zsh/datetime b:strftime

save_path_to_cache ()
{
    local dest="$HOME/.path-carapace"
    local tmp="${dest}.$$"
    local now

    TZ=UTC strftime -s now "%a %b %e %H:%M:%S UTC %Y" $EPOCHSECONDS

    print -r -- "#
# Path cache file
#
# Generated: ${now}
#

export PATH=\"$PATH\"
" > "$tmp" && mv -f "$tmp" "$dest"
}

#
# Source profile
#

. "$HOME/.profile"

# Disable ^S/^Q flow control
[[ $- == *i* ]] && stty -ixon

#
# Set umask
#
umask 022

#
# Set timezone
#

# Allow it to be overridden at the host
if [ -r "$HOME/.host/timezone" ]; then
    . "$HOME/.host/timezone"
else
    export TZ='America/New_York'
fi

#
# Load system-level environment stuff
#

# NOTE: read in-process rather than forking cat.  Skips comments and blanks;
# the old version exported them and anything else on the line.
if [ -r /etc/environment ]; then
    while IFS= read -r line; do
        case "$line" in
            ''|'#'*) continue ;;
            *=*)     export "$line" ;;
        esac
    done < /etc/environment
fi

#
# Path Helper Functions
#

# Add to the end of the path.  Doesn't check for duplicates
add_path_back ()
{
    if [[ -d "$*" ]]; then
        if [[ -n "$PATH" ]]; then
            export PATH="$PATH:$*"
        else
            export PATH="$*"
        fi
    fi
}

# Add to the beginning of the path.  Doesn't check for duplicates
add_path_front ()
{
    if [[ -d "$*" ]]; then
        if [[ -n "$PATH" ]]; then
            export PATH="$*:$PATH"
        else
            export PATH="$*"
        fi
    fi
}

# Homebrew variables
#
# NOTE: the first candidate used to be the bare word "brew", which `[ -x ]`
# resolves as a relative path, not a $PATH search -- it never matched.
#
# `brew shellenv` is a bash script that takes ~80ms to print eight exports that
# only change when Homebrew itself moves.  Cache it, and regenerate when the
# brew executable is newer than the cache.
brewcmds=( ${commands[brew]} /opt/homebrew/bin/brew "${HOME}/homebrew/bin/brew" /home/linuxbrew/.linuxbrew/bin/brew "${HOME}/.brew/bin/brew" )
for brewcmd in ${brewcmds}; do
  if [ -x "${brewcmd}" ]; then
    export CARAPACE_BREW_CMD="${brewcmd}"

    _brew_env_cache="${HOME}/.cache/carapace/brew-shellenv.zsh"
    if [[ ! -r $_brew_env_cache || $CARAPACE_BREW_CMD -nt $_brew_env_cache ]]; then
      mkdir -p "${_brew_env_cache:h}" 2>/dev/null || :
      "$CARAPACE_BREW_CMD" shellenv > "$_brew_env_cache" 2>/dev/null || :
    fi
    if [[ -s $_brew_env_cache ]]; then
      source "$_brew_env_cache"
    else
      eval "$(${CARAPACE_BREW_CMD} shellenv)"
    fi
    unset _brew_env_cache

    break
  fi
done

#
# Zsh Functions
#

# Add to the end of the fpath.  Doesn't check for duplicates
add_fpath_back ()
{
    if [[ -d "$*" ]]; then
        if [[ -n "$FPATH" ]]; then
            export FPATH="$FPATH:$*"
        else
            export FPATH="$*"
        fi
    fi
}

# Add to the beginning of the fpath.  Doesn't check for duplicates
add_fpath_front ()
{
    if [[ -d "$*" ]]; then
        if [[ -n "$FPATH" ]]; then
            export FPATH="$*:$FPATH"
        else
            export FPATH="$*"
        fi
    fi
}

# Update function search path
func_candidates=("$(dirname $(which zsh))/../share/zsh" "${HOMEBREW_PREFIX}/share/zsh" "/usr/share/zsh")
for f in ${func_candidates}; do
  for d in "functions" "site-functions"; do
    if [ -d "${f}/${d}" ]; then
      add_fpath_back "${f}/${d}"
    fi
  done
done

# Autoloads
autoload -U is-at-least

#
# Set up some paths
#

export PATH=""

add_path_back "$HOME/bin"
add_path_back "$HOME/bin/carapace"
add_path_back "$HOME/.local/bin"
add_path_back "$HOME/.cargo/bin"

# Homebrew
for prog in coreutils findutils grep gawk; do
  add_path_back "${HOMEBREW_PREFIX}/opt/${prog}/libexec/gnubin"
done
for gnuprog in sed time indent which tar ; do
  add_path_back "${HOMEBREW_PREFIX}/opt/gnu-${gnuprog}/libexec/gnubin"
done
for prog in llvm; do
  add_path_back "${HOMEBREW_PREFIX}/opt/${prog}/bin"
done
add_path_back "${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin"
add_path_back "${HOMEBREW_PREFIX}/bin"
add_path_back "${HOMEBREW_PREFIX}/sbin"

add_path_back "/Users/cheilman/.opencode/bin"

add_path_back "/snap/bin"
add_path_back "/usr/local/bin"
add_path_back "/usr/bin"
add_path_back "/bin"
add_path_back "/usr/local/sbin"
add_path_back "/usr/sbin"
add_path_back "/sbin"
add_path_back "/usr/X11R6/bin"
add_path_back "/usr/X11/bin"
add_path_back "$HOME/programs/games"
add_path_back "/usr/games"
add_path_back "/usr/local/games"
add_path_back "/Applications/Docker.app/Contents/Resources/bin"

#
# Colors
#

autoload colors
colors

#
# Color definitions (taken from Color Bash Prompt HowTo).
# Some colors might look different of some terminals.
# For example, I see 'Bold Red' as 'orange' on my screen,
# hence the 'Green' 'BRed' 'Red' sequence I often use in my prompt.
#

for COLOR in Black Red Green Yellow Blue Magenta Cyan White; do
    eval $COLOR='%{$fg_no_bold[${(L)COLOR}]%}'
    eval B$COLOR='%{$fg_bold[${(L)COLOR}]%}'
    eval On_$COLOR='%{$bg[${(L)COLOR}]%}'
done
eval RESET='%{$reset_color%}'

# Colors are ${Color} or ${BColor} for bold.
NC=${RESET}

ALERT=${BWhite}${On_Red} # Bold White on red background

#################
# Shell Options #
#################

#
# Key bindings
#

# emacs bindings
bindkey -e

# ctrl + left/right go forward/backwords words
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word

# del/home/end
bindkey '^[[3~' delete-char
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line

# push current command to the stack, give blank line, after execution
# original command pops back out
bindkey "^X^T" push-line-or-edit

# delete previous word (include path components as 'words')
# http://www.zsh.org/mla/users/2001/msg00870.html
tcsh-backward-delete-word () {
    local WORDCHARS="${WORDCHARS:s#/#}"
    zle backward-delete-word
}
zle -N tcsh-backward-delete-word
bindkey '^H' tcsh-backward-delete-word

#
# Changing directories
#
setopt AUTO_PUSHD

#
# Completion
#
setopt AUTO_LIST
unsetopt AUTO_NAME_DIRS
setopt ALWAYS_TO_END
unsetopt GLOB_COMPLETE
setopt LIST_AMBIGUOUS
unsetopt LIST_BEEP
setopt LIST_TYPES

#
# Expansion and Globbing
#

#
# Initialization
#

#
# Input/Output
#
setopt ALIASES
setopt CLOBBER
setopt CORRECT
unsetopt CORRECT_ALL
unsetopt FLOW_CONTROL
unsetopt MAIL_WARNING

#
# Job Control
#
unsetopt BG_NICE
setopt CHECK_JOBS
setopt LONG_LIST_JOBS
setopt NOTIFY

#
# Prompting
#
setopt PROMPT_CR
setopt PROMPT_SP
setopt PROMPT_PERCENT
setopt PROMPT_SUBST

#
# Scripts and Functions
#
setopt C_BASES
setopt C_PRECEDENCES

#
# Shell Emulation
#

#
# Zle
#
unsetopt BEEP

