#!/usr/bin/env zsh
#
# Package up carapace-minimal for use later
#

moduledir="${1:-/dev/null}"
generateddir="${2:-/dev/null}"

carapaceminimal="${moduledir}/carapace-minimal"

# Compute hash of minimal install (to use as a version)
rm -f "$carapaceminimal/version" "$carapaceminimal/metadata"

version="$(hash-directory "$carapaceminimal")"

echo $version > "$carapaceminimal/version"

dt="$(date)"
which gdate &>/dev/null
if [ $? -eq 0 ]; then
  dt="$(gdate --iso-8601=seconds)"
fi
echo "Build date: ${dt}" > "$carapaceminimal/metadata"

# Build tarball
(cd $(dirname "$carapaceminimal") && tar hzcf "${generateddir}/carapace-minimal.tar.gz" carapace-minimal)

