#!/usr/bin/env zsh
#
# Get and install the executable
#

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

repo="github.com/cheilman/sysdash"

# Load go environment
source "${HOME}/bin/carapace/goenv-cache"

if [ -d "$GOPATH" -a -x "$(which go 2> /dev/null)" ]; then
    ${GOROOT}/bin/go get -u "$repo"
fi

