#!/usr/bin/env zsh
#
# Get and install the executable
#

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

if [ -r "$HOME/.host/config/skip_goutils" ]; then
    carapace-message "magenta" "Skipping all go utilities due to host config flag."
    exit
fi

# TODO: This is broken for now
#
#repo="github.com/cheilman/sysdash@latest"
#
## Load go environment
#source "${HOME}/bin/carapace/goenv-cache"
#
#if [ -d "$GOPATH" -a -x "$(which go 2> /dev/null)" ]; then
#    ${GOROOT}/bin/go install "$repo"
#fi
#
