#!/usr/bin/env zsh
#
# Get and install the executables for useful go utilities
#

moduledir="${1:-/dev/null}"
generateddir="${2:-/dev/null}"

if [ -r "$HOME/.host/config/skip_goutils" ]; then
  carapace-message "magenta" "Skipping all go utilities due to host config flag."
  exit
fi

# Load go environment
source "${HOME}/bin/carapace/goenv-cache"

# Install a bunch of go repos
repos=(
  "github.com/Feh/guess@latest"
  "github.com/evanmiller/hecate@latest"
  "github.com/maxzender/jv@latest"
  "github.com/pranavraja/tldr@latest"
  )

if [ -d "$GOPATH" -a -x "$(which go 2> /dev/null)" ]; then
    export CARAPACE_INDENT="  ${CARAPACE_INDENT}"

    for i in $repos; do
        (
            ${GOROOT}/bin/go install "$i"
            if [ $? -ne 0 ]; then
                carapace-message "himagenta" "Failed to install go utility: $i"
            else
                carapace-message "green" "installed: ${i:t}"
            fi
        )
    done

    export CARAPACE_INDENT="${CARAPACE_INDENT:2}"
fi

