#!/usr/bin/env zsh
#
# Install go
#

autoload is-at-least

moduledir="${1:-/dev/null}"
generateddir="${2:-/dev/null}"

goenv_cache="${moduledir}/bin/goenv-cache"

arch="linux-amd64"
desired_version="1.16"

export GOPATH="$HOME/go"

#
# Try to detect a go install of the correct version
# NOTE: Highest version number wins, preference is given to items earlier in the list
#
install_locations=( "${GOROOT}/bin/go" "/usr/lib/google-golang/bin/go" "/usr/local/bin/go" "/usr/bin/go" "/bin/go" "${HOMEBREW_PREFIX}/bin/go" "${moduledir}/go/bin/go" )
found_goroot=""
currentver=""

for i in ${install_locations}; do
    if [ -x "$i" ]; then
        foundver="$( /usr/bin/env -i GOPATH=$GOPATH ${i} version 2> /dev/null | grep -Eoe '([0-9]+\.)+[0-9]+' )"
        if is-at-least "${desired_version}" "${foundver}" && is-at-least "${currentver}" "${foundver}"; then
            # Grab the go root
            found_goroot="$( /usr/bin/env -i GOPATH=$GOPATH "${i}" env | grep GOROOT | cut -d= -f2 | cut -d\" -f2 | cut -d\' -f2 )"
            currentver=${foundver}
        fi
    fi
done

#
# Did we find a go installation?
#

if [ -d "${found_goroot}" -a -x "${found_goroot}/bin/go" ]; then
    # Assuming we have it discovered, save the environment details for later
    carapace-message "cyan" "found go ${currentver} at ${found_goroot}"

    if [ -r "$HOME/.host/config/disable_goproxy" ]; then
      carapace-message "yellow" "Setting GOPROXY to direct..."
      /usr/bin/env -i GOPATH=$GOPATH "${found_goroot}/bin/go" env -u GOPROXY 2> /dev/null
      /usr/bin/env -i GOPATH=$GOPATH "${found_goroot}/bin/go" env -w GOPROXY=direct 2>/dev/null
    fi

    /usr/bin/env -i GOPATH=$GOPATH "${found_goroot}/bin/go" env | grep '^GO' | grep -v GOPATH | sed -e 's/^/export /' > "${goenv_cache}"

    # There are new GOCACHE requirements that don't always show up in the 'env'
    mkdir -p "$HOME/tmp/gocache" &>/dev/null || :
    echo "export GOCACHE='$HOME/tmp/gocache'" >> "${goenv_cache}"

    if [ -r "$HOME/.host/config/disable_goproxy" ]; then
      carapace-message "yellow" "Removing Google's go proxy url from goenv-cache..."
      sed -e 's;https://proxy.golang.org,;;' -i "${goenv_cache}"
    fi
else
    carapace-message "boldred" "Failed to find an approprite go installation under '${found_goroot}'!"
    exit 1
fi

