#!zsh
#
# My go installation
#

# This should be after $GOROOT/bin, so that we use a local version before OS version
add_path_front "/usr/local/go/bin"

if [ -d "${CARAPACE_CURRENT_MODULE_PATH}/go" ]; then
    # Install succeeded
    export GOROOT="${CARAPACE_CURRENT_MODULE_PATH}/go"
    add_path_front "$GOROOT/bin"
fi

#
# My go workspace and path
#

if [ -z "$GOPATH" -a -d "$HOME/go" ]; then
    export GOPATH=$HOME/go
fi

if [ -n "$GOPATH" ]; then
    add_path_front "$GOPATH/bin"
fi

