#!zsh
#
# My go installation
#

# The installer writes go information into a cache file
goenv_cache="${HOME}/bin/carapace/goenv-cache"

if [ -r "${goenv_cache}" ]; then
    source "${goenv_cache}"
fi

# Did we find go anywhere?
if [ -d "$GOROOT" ]; then
    # This should be after $GOROOT/bin, so that we use a local version (if installed) before OS version
    add_path_front "/usr/local/go/bin"
    add_path_front "$GOROOT/bin"

    #
    # My go workspace and path
    #

    mkdir $HOME/go 2> /dev/null || :
    mkdir $HOME/go/bin 2> /dev/null || :

    if [ -z "$GOPATH" -a -d "$HOME/go" ]; then
        export GOPATH=$HOME/go
    fi

    if [ -n "$GOPATH" ]; then
        add_path_front "$GOPATH/bin"
    fi

    if [ -r "$HOME/.host/config/disable_goproxy" ]; then
      /usr/bin/env -i GOPATH=$GOPATH "${found_goroot}/bin/go" env -u GOPROXY 2> /dev/null
      /usr/bin/env -i GOPATH=$GOPATH "${found_goroot}/bin/go" env -w GOPROXY=direct 2>/dev/null
    fi
fi

# Add a default gopath just in case we have detection issues
add_path_back "${HOME}/go/bin"

