#!/usr/bin/env zsh
#
# Get and install the executable
#

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

repo="github.com/cheilman/sysdash"

if [ -d "$GOPATH" -a -x "$(which go 2> /dev/null)" ]; then
    ${moduledir}/../10go/go/bin/go get -u "$repo"
fi

