#!/bin/bash
#
# Run every ssh connection
#

# Try to link our ssh agent to a known location (helps w/ tmux)
# From: https://gist.github.com/martijnvermaat/8070533
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# Make X11 forwarding work right
# From: sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi

