#!/usr/bin/env zsh

#
# Configure zgen and plugins
#

moduledir="${1:-${0:a:h}}"

# zgen
export ZGEN_DIR=${moduledir}/zgen

# alias-tips configuration
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="_"

#
# Load zgen stuff
#

source $ZGEN_DIR/zgen.zsh

#
# Enable run-once
#

zgen reset

zgen load zsh-users/zsh-syntax-highlighting
zgen load zsh-users/zsh-autosuggestions
zgen load zsh-users/zsh-completions

zgen load romkatv/powerlevel10k powerlevel10k

zgen load unixorn/autoupdate-zgen

zgen load popstas/zsh-command-time

zgen oh-my-zsh
zgen oh-my-zsh plugins/safe-paste

bgnotify_threshold=15
zgen oh-my-zsh plugins/bgnotify

zgen oh-my-zsh plugins/catimg

zgen oh-my-zsh plugins/colorize

zgen oh-my-zsh plugins/copybuffer
zgen oh-my-zsh plugins/copypath
zgen oh-my-zsh plugins/copyfile

zgen oh-my-zsh plugins/emoji-clock

zgen oh-my-zsh plugins/golang

zgen oh-my-zsh plugins/httpie

zgen save

