#!/usr/bin/env zsh
#
# Grab/update the repo
#

repodir="zgen"
repo="https://github.com/tarjoilija/zgen.git"

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

carapace-redirect "${moduledir}/zgen" "$HOME/.zgen"

# See if we're already installed
if [ -d "${moduledir}/${repodir}" ]; then
    # Assume the repo exists, update it
    ( cd "${moduledir}/${repodir}" && git pull -q --recurse-submodules )

    # Update the plugins and remove init script (forcing regeneration)
    if which zgen &>/dev/null; then
      zgen update
    fi
else
    # Assume the repo does not exist
    ( cd "${moduledir}" && git clone --recurse-submodules "${repo}" ./${repodir} )
fi


