#!zsh
#
# Use carapaceprompt if installed, default to something terrible otherwise
#

# Hook for additional prompt params
carapace_prompt_additional_params() {
  echo ""
}

# Wrapper that adds shell-based flags to the prompt
carapace_prompt_wrapper() {
    local exitcode=$1
    local running=""
    local suspended=""
    local battery=""
    local jbs="$(jobs 2>/dev/null)"
    local extra="$(carapace_prompt_additional_params)"

    [[ "$jbs" =~ "run" ]] && running="--runningjobs"
    [[ "$jbs" =~ "sus" ]] && running="--suspendedjobs"
    [ -x "$(which ibam-battery-prompt 2>/dev/null)" ] && battery="--showBattery"

    carapaceprompt --color --exitcode $exitcode $running $suspended $battery "${=extra}"
}

if [ -x "$(which carapaceprompt 2> /dev/null)" ]; then
    export PS1='%{$(carapace_prompt_wrapper $?)%}
${Green}--${BCyan}%#${NC} '

else
    export PS1='${Green}--${BCyan}%#${NC} '
fi

