#!/usr/bin/env zsh

#
# Configure zgen and plugins
#

# zgen
export DISABLE_AUTO_UPDATE=true

export ZGEN_DIR=${CARAPACE_CURRENT_MODULE_PATH}/zgen

# zsh-syntax-highlighting
# config and styles: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets root)
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow,bold'

# alias-tips configuration
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="_"

#
# Load zgen stuff
#

source $ZGEN_DIR/zgen.zsh

#
# Enable run-once
#
if ! zgen saved; then
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-autosuggestions

    #zgen load djui/alias-tips

    zgen load rbirnie/oh-my-zsh-keybase

    zgen load unixorn/autoupdate-zgen

    zgen oh-my-zsh
    zgen oh-my-zsh plugins/safe-paste
    #zgen oh-my-zsh plugins/docker
    #zgen oh-my-zsh plugins/gitfast
    #zgen oh-my-zsh plugins/mvn
    #zgen oh-my-zsh plugins/sudo
    #zgen oh-my-zsh plugins/git

    zgen save
fi

