#!/usr/bin/env zsh
#
# Grab/update the repo
#

repodir="zgenom"
repo="https://github.com/jandamm/zgenom.git"

moduledir="${1:-${0:a:h}}"
generated="${2:-/dev/null}"

# See if we're already installed
if [ -d "${moduledir}/${repodir}" ]; then
    # Assume the repo exists, update it
    ( cd "${moduledir}/${repodir}" && git pull -q --recurse-submodules )

    # Update the plugins and remove init script (forcing regeneration)
    if which zgenom &>/dev/null; then
      zgenom selfupdate
      zgenom update
    fi
else
    # Assume the repo does not exist
    ( cd "${moduledir}" && git clone --recurse-submodules "${repo}" ./${repodir} )
fi

carapace-redirect "${moduledir}/zgenom" "$HOME/.zgenom"

