#!/usr/bin/env zsh
#
# Updatea carapace module.
#
# Usage: carapace-update-module <module name> <module directory>
#

set -e

#
# Setup
#

modulefullname="$1"
moduledir="$2"
modulepriority="${${modulefullname}:0:2}"
module="$(echo ${${modulefullname}:2} | cut -d- -f1)"
bundlename="$(echo ${modulefullname} | cut -d- -f2)"

modulename="${bundlename}/${module}"

# See carapace-install-module.
: ${CARAPACE_SKIP:=42}

carapace-message "boldblue" "processing module [${modulepriority}] ${modulename}"

export CARAPACE_INDENT="  ${CARAPACE_INDENT}"

TRAPEXIT() {
    export CARAPACE_INDENT="${CARAPACE_INDENT:2}"
}

#
# Execute update script
#

if [ -x "${moduledir}/update" ]; then
    # See the note in carapace-install-module: `|| err=$?` keeps `set -e` from
    # swallowing the distinction between "not applicable" and "broken".
    err=0
    ${moduledir}/update "$moduledir" || err=$?

    if [ $err -eq $CARAPACE_SKIP ]; then
        carapace-message "boldbrown" "Skipping '$modulename' (not applicable on this host)"
        exit 0
    elif [ $err -ne 0 ]; then
        carapace-message "boldred" "'$modulename' update script failed: $err"
        exit $err
    fi
elif [ -e "${moduledir}/update" ]; then
    carapace-message "hired" "Warning, '$modulename' has an update file that is NOT executable."
fi

#
# All done!
# Append module name as a success!
#

carapace-message "boldgreen" "$modulename updated successfully"

if [ -z "$CARAPACE_MODULES" ]; then
    export CARAPACE_MODULES="${modulename}"
else
    export CARAPACE_MODULES="${CARAPACE_MODULES},${modulename}"
fi
