#!/usr/bin/env zsh
#
# Generate and install all the Carapace files
#
set -e

#
# Prepare
#

# Try to autodetect carapace folder
export CARAPACE="${0:A:h:h}"

if [ ! -d "$CARAPACE" ]; then
    export CARAPACE="$HOME/.carapace"

    if [ ! -d "$CARAPACE" ]; then
        >&2 echo "Unable to find carapace folder!"
        exit 1
    fi
fi

export PATH="$CARAPACE/install:$PATH"
export CARAPACE_GENERATED="$CARAPACE/generated"
export CARAPACE_GENERATED_INTERMEDIATE="$CARAPACE/generated/intermediate"
export CARAPACE_MODULES=""
export CARAPACE_INDENT=""

carapace-message "boldcyan" "Carapace Installation Starting..."
export CARAPACE_INDENT=" >"
carapace-message "cyan" "using source folder '$CARAPACE'"

#
# Create any necessary folders that might not exist yet.
#

carapace-message "cyan" "creating necessary folders"

mkdir -p "$HOME/bin/carapace" &> /dev/null || :
mkdir -p "$CARAPACE_GENERATED_INTERMEDIATE" &> /dev/null || :
mkdir -p "$HOME/.config" &> /dev/null || :
mkdir -p "$HOME/.ssh" --mode 700 &> /dev/null || :
mkdir -p "$HOME/.host/config" &> /dev/null || :
mkdir -p "$HOME/.host/modules" &> /dev/null || :
mkdir -p "$HOME/.host/bin" &> /dev/null || :

#
# Functions
#

#
# Populate some readmes for local host settings
#

if [ ! -f "$HOME/.host/README.md" ]; then
    carapace-redirect "$CARAPACE/docs/Host.md" "$HOME/.host/README.md"
fi

if [ ! -f "$HOME/.host/config/README.md" ]; then
    carapace-redirect "$CARAPACE/docs/Host-Config.md" "$HOME/.host/config/README.md"
fi

#
# Install our installation and update files
#

carapace-redirect "$CARAPACE/install/carapace-install" "$HOME/bin/carapace/carapace-install"
carapace-redirect "$CARAPACE/install/carapace-update" "$HOME/bin/carapace/carapace-update"

#
# Start by creating the boilerplate/headers for the generated files
#

carapace-message "cyan" "setting up generated file boilerplate"
for i in crontab gitconfig gitignore i3config profile ssh_config zshrc hgrc hgignore; do
    cp $CARAPACE/docs/templates/$i-template $CARAPACE_GENERATED_INTERMEDIATE/generated-$i

    echo "#" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-$i
    echo "# Generated: $(date -u)" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-$i
    echo "#" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-$i
    echo >> $CARAPACE_GENERATED_INTERMEDIATE/generated-$i
done

( # vimrc
    cp $CARAPACE/docs/templates/vimrc-template $CARAPACE_GENERATED_INTERMEDIATE/generated-vimrc

    echo "\"" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-vimrc
    echo "\" Generated: $(date -u)" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-vimrc
    echo "\"" >> $CARAPACE_GENERATED_INTERMEDIATE/generated-vimrc
    echo >> $CARAPACE_GENERATED_INTERMEDIATE/generated-vimrc
)

#
# Run through the bundles and link their modules
#
(
    carapace-message "cyan" "evaluating bundles"
    export CARAPACE_INDENT="  ${CARAPACE_INDENT}"

    cd $CARAPACE/bundles
    for i in *; do
        if [ -d "$i" ]; then
            carapace-message "boldblue" "processing bundle $i"

            carapace-install-bundle "$(readlink -f $i)" "$CARAPACE/modules" "$CARAPACE_GENERATED_INTERMEDIATE" || (
                carapace-message "boldred" "$i bundle failed!"
            )
        fi
    done

    if [ -d "$HOME/.host/modules" ]; then
        carapace-message "boldblue" "processing bundle HOST"

        carapace-install-bundle "$(readlink -f "$HOME/.host/modules")" "$CARAPACE/modules" "$CARAPACE_GENERATED_INTERMEDIATE" "HOST" || (
                carapace-message "boldred" "HOST bundle failed!"
            )
    fi

    export CARAPACE_INDENT="${CARAPACE_INDENT:2}"
)

#
# Now start checking modules
#
module_failed=0

(
    err=0
    carapace-message "cyan" "evaluating modules"
    export CARAPACE_INDENT="  ${CARAPACE_INDENT}"

    cd $CARAPACE/modules
    for i in *; do
        if [ -d "$i" ]; then
            carapace-install-module "$i" "$(readlink -f $i)" "$CARAPACE_GENERATED_INTERMEDIATE" || {
                carapace-message "boldred" "$i module failed!"
                err=1
            }
        fi
    done

    export CARAPACE_INDENT="${CARAPACE_INDENT:2}"

    exit $err
) || module_failed=1

#
# Finalize zshrc
#

cat >> "${CARAPACE_GENERATED_INTERMEDIATE}/generated-zshrc" <<EOF
#############################
# Module Inclusion Finished #
#############################

EOF

# Clear module-level variables
cat >> "${CARAPACE_GENERATED_INTERMEDIATE}/generated-zshrc" <<EOF

#
# Clearing module variables
#
export CARAPACE_CURRENT_MODULE=""
export CARAPACE_CURRENT_MODULE_PATH=""

EOF

#
# Clean up old generated files and move the new ones into place
#

# NOTE: We only want to deleted the generated files, keep the timestamps or it may cause trouble
carapace-message "cyan" "clearing old generated files"
if [ -d "${CARAPACE_GENERATED}" -a -e "${CARAPACE_GENERATED}/generated-zshrc" ]; then
    rm -f $CARAPACE_GENERATED/generated* &> /dev/null || :
fi

carapace-message "cyan" "installing new generated files"
mv "${CARAPACE_GENERATED_INTERMEDIATE}"/* "${CARAPACE_GENERATED}/"

#
# Link up our generated files
#

carapace-redirect "$CARAPACE_GENERATED/generated-gitconfig" "$HOME/.gitconfig"
carapace-redirect "$CARAPACE_GENERATED/generated-gitignore" "$HOME/.gitignore"
carapace-redirect "$CARAPACE_GENERATED/generated-hgrc" "$HOME/.hgrc"
carapace-redirect "$CARAPACE_GENERATED/generated-hgignore" "$HOME/.hgignore"
carapace-redirect "$CARAPACE_GENERATED/generated-profile" "$HOME/.profile"
carapace-redirect "$CARAPACE_GENERATED/generated-ssh_config" "$HOME/.ssh/config"
carapace-redirect "$CARAPACE_GENERATED/generated-vimrc" "$HOME/.vimrc"

if [ -d "$HOME/.i3" ]; then
    carapace-redirect "$CARAPACE_GENERATED/generated-i3config" "$HOME/.i3/config"
fi

# Zshrc links to the script that updates Carapace first
carapace-redirect "$CARAPACE/zshrc-update" "$HOME/.zshrc"

#
# Install crontab
#

crontab "$CARAPACE_GENERATED/generated-crontab"

#
# Should be all good!
#

export CARAPACE_INDENT="${CARAPACE_INDENT:2}"
carapace-message "boldcyan" "Carapace Installation Complete!"

if [ $module_failed -ne 0 ]; then
    carapace-message "boldred" "One or more modules failed!"
    exit 1
fi

