#!/usr/bin/env zsh
#
# Update the Carapace system and re-install
#
set -e

#
# Prepare
#

# Try to autodetect carapace folder
export CARAPACE="${0:A:h:h}"

if [ ! -d "$CARAPACE" ]; then
    export CARAPACE="$HOME/.carapace"

    if [ ! -d "$CARAPACE" ]; then
        >&2 echo "Unable to find carapace folder!"
        exit 1
    fi
fi

export PATH="$CARAPACE/install:$PATH"

#
# Update main folder
#

carapace-message "boldcyan" "Carapace Update Starting on folder '$CARAPACE' ..."
( cd $CARAPACE && git pull -q --recurse-submodules )

#
# Update bundles
#
(
    carapace-message "cyan" "evaluating bundles"
    export CARAPACE_INDENT="  ${CARAPACE_INDENT}"

    cd $CARAPACE/bundles
    for i in *; do
        if [ -d "$i" ]; then
            carapace-message "boldblue" "updating bundle $i"

            # Update bundle if it has its own repo
            (
                cd $i

                if [ -d "./.git" ]; then
                    git pull -q --recurse-submodules
                fi
            )

        fi
    done

    export CARAPACE_INDENT="${CARAPACE_INDENT:2}"
)

#
# Done
#

carapace-message "boldcyan" "Carapace Update Finished"

#
# Reinstall
#

carapace-install
