#!/usr/bin/env bash

#
# Locate the carapace installation folder
#

zshrc="${HOME}/.zshrc"
if [ -h "$zshrc" ]; then
  # zshrc is a link into carapace
  carapace="$(dirname "$(readlink -f "$zshrc")")"
  if [ -f "${carapace}/CARAPACE" ]; then
    readlink -f "${carapace}"
    exit 0
  fi
fi

# zshrc is a plain file, or missing...
# try to guess where carapace is
for i in "${HOME}/.carapace" "${HOME}/carapace"; do
  if [ -f "${i}/CARAPACE" ]; then
    readlink -f "${i}"
    exit 0
  fi
done

exit 1

