"
" Finalize vimrc settings
"

" This has to be last to enable all plugins
filetype plugin indent on
syntax on

" Now do our highlighting
highlight CursorLine cterm=NONE ctermbg=black
highlight CursorLineNR cterm=underline ctermbg=black

" Force line numbers
set number

" Maybe now do go formatting?  use 4-space tab width, while still using tabs
au BufNewFile,BufRead *.go setlocal noet ts=4 sw=4 sts=4

