wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  exitMessage:
    display: false
  navigation:
    shortcuts: false
  grid:
    # How _wide_ the columns are, in terminal characters.
    columns: [-1, -1, -1, -1]
    # How _high_ the rows are, in terminal lines.
    rows: [-3, -2, -2, -2, -2]
  refreshInterval: 1s
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    big_clock:
      title: "Now!"
      type: digitalclock
      color: blue
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      hourFormat: 24
      font: digitalfont
      refreshInterval: 1s
      withDatePrefix: false
    clocks:
      title: "Clocks"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Pittsburgh: "America/New_York"
        WestCoast: "America/Los_Angeles"
        UTC: "Etc/UTC"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15s
      sort: "natural"
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 15s
    security:
      enabled: true
      type: security
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 30m
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 1
        left: 3
        height: 4
        width: 1
      refreshInterval: 1s
      #cpuCombined: true
      cpuCombined: false
      graphIcon: "█"
    carapaceGitDash:
      type: cmdrunner
      enabled: true
      position:
        top: 1
        left: 0
        height: 2
        width: 3
      refreshInterval: 60s
      args: []
      cmd: 'git-dashboard'
    carapaceHgDash:
      type: cmdrunner
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 3
      refreshInterval: 60s
      args: []
      cmd: 'hg-dashboard'
