#!zsh
#
# Set up grc
#

# From Ivan Smirnov

# Grc plugin
# Uses config from ~/.grc
# vim:ft=zsh
# NOTE: this widget runs on every Enter.  It used to fork `ls ~/.grc/conf*`
# each time and then walk ~74 configs.  Build the list once, at startup.
typeset -ga _grc_progs=( ~/.grc/conf*(N:e) )

_grc_injector(){
  if (( ! ${+DISABLE_GRC} )); then
    if [[ ! "$BUFFER" =~ "grcat conf*" ]]; then
      local prog
      for prog in $_grc_progs; do
        if [[ "$BUFFER" =~ "(^|[/\w\.]+/|sudo\s+)$prog\s" ]]; then
          BUFFER=$BUFFER" | grcat conf.$prog"
          break
        fi
      done
    fi
  fi
  zle .accept-line
}
zle -N accept-line  _grc_injector

