#!zsh
#
# Set up grc
#

# From Ivan Smirnov

# Grc plugin
# Uses config from ~/.grc
# vim:ft=zsh
_grc_injector(){
  if (( ! ${+DISABLE_GRC} )); then
    for f in $(ls ~/.grc/conf*); do
      local prog=${f:e}
      if [[ "$BUFFER" =~ "(^|[/\w\.]+/|sudo\s+)$prog\s" && ! "$BUFFER" =~ "grcat conf*" ]]; then
        BUFFER=$BUFFER" | grcat conf.$prog"
        break
      fi
    done
  fi
  zle .accept-line
}
zle -N accept-line  _grc_injector

